apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-morning-api
  labels:
    app: cloud-morning-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-morning-api
  template:
    metadata:
      labels:
        app: cloud-morning-api
    spec:
      containers:
      - name: cloud-morning-api
        image: acrcloudmorningdemo.azurecr.io/anp-demo-iac-governance:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-morning-api
spec:
  selector:
    app: cloud-morning-api
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer
