apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsquad-api
  labels:
    app: devsquad-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devsquad-api
  template:
    metadata:
      labels:
        app: devsquad-api
    spec:
      containers:
      - name: devsquad-api
        image: acrdevsquaddemo.azurecr.io/devsquad-api:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: devsquad-api
spec:
  selector:
    app: devsquad-api
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer
