---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloud-morning-api
  name: cloud-morning-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-morning-api
  template:
    metadata:
      labels:
        app: cloud-morning-api
    spec:
      containers:
      - image: acrcloudmorningdemo.azurecr.io/anp-demo-iac-governance:latest
        name: cloud-morning-api
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-morning-api
spec:
  ports:
  - port: 8081
  selector:
    app: cloud-morning-api
  type: LoadBalancer
