trigger:
- none

resources:
- repo: self

variables:
  imageRepository: 'devsquad-api'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  vmImageName: 'ubuntu-latest'

steps:
- task: Docker@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'azureconn'
    azureContainerRegistry: 'acrdevsquaddemo.azurecr.io'
    action: 'Build an image'
    dockerFile: '**/Dockerfile'
    imageName: '$(Build.Repository.Name):$(Build.BuildId)'
    includeLatestTag: true
- task: Docker@0
  displayName: 'Push a container image'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'MSDN Platforms Subscription(1)(9d875e89-86f8-47d1-99b2-be3fea5d8523)'
    azureContainerRegistry: '{"loginServer":"acrdevsquaddemo.azurecr.io", "id" : "/subscriptions/9d875e89-86f8-47d1-99b2-be3fea5d8523/resourceGroups/rg_devsquad-deploy/providers/Microsoft.ContainerRegistry/registries/acrdevsquaddemo"}'
    action: 'Push an image'
    imageName: '$(Build.Repository.Name):$(Build.BuildId)'
    includeLatestTag: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: 'deployments/deployment.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts: drop'    