trigger:
  - none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'src/iac'
    #backendServiceArm: 'MSDN Platforms Subscription(9d875e89-86f8-47d1-99b2-be3fea5d8523)'
    backendServiceArm: 'azureconn'
    backendAzureRmResourceGroupName: 'rg_devsquad'
    backendAzureRmStorageAccountName: 'storageterraformdevsquad'
    backendAzureRmContainerName: 'containerterraformdevsquad'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: 'src/iac'
    environmentServiceNameAzureRM: 'azureconn'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: 'src/iac'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'azureconn'