trigger:
  - none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'src/iac'
    backendServiceArm: 'cloud-morning-demo'
    backendAzureRmResourceGroupName: 'rg-cloud-morning-demo'
    backendAzureRmStorageAccountName: 'terraformcloudmorning'
    backendAzureRmContainerName: 'containerterraformcloudmorning'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: 'src/iac'
    environmentServiceNameAzureRM: 'cloud-morning-demo'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: 'src/iac'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'cloud-morning-demo'